### ISSUE TITLE
I dont think its sending custom images

### ISSUE THREAD

**Issue by Gianni-Ingurgio** [HelloWorld017/atom-discord#105]
## Step to reproduce
1.   Set a custom client ID with all filetype icons uploaded
2.   Set a custom image
3.   Check Discord console
4.   Notice that only the non-custom image has an image ID

## Information
**Platform**: Windows 10  
**Atom**: 1.49.0
**Package Version**: 2.0.2

## output in discord console (ctrl shift I)
This is with a cusom image set
```
[RPCServer:IPC] Socket Emit: 1360 
  {cmd: "SET_ACTIVITY", data: {…}, evt: null, nonce: "1234567890abcdefgijkl"}
  cmd: "SET_ACTIVITY"
  data:
    application_id: "123456789101112"
    assets:
      large_text: "Editing a Markdown file"
      small_image: "123456789101112"
      small_text: "Editing README.md"
      __proto__: Object
    details: "Working on code"
    name: "Code"
    state: "Editing README.md"
    timestamps: {start: 1595529231000}
    __proto__: Object
    evt: null
  nonce: "1234567890abcdefgijkl"
  __proto__: Object
```
This is with a non-custom image set
```
[RPCServer:IPC] Socket Emit: 1360 
{cmd: "SET_ACTIVITY", data: {…}, evt: null, nonce: "abcdefgijkl1234567890"}
  cmd: "SET_ACTIVITY"
  data:
    application_id: "123456789101112"
    assets:
      large_image: "123456789101112"
      large_text: "Blissful Ignorance"
      small_text: "Working with Atom"
      __proto__: Object
    details: "Not working on Skribbl.io"
    name: "Code"
    state: "Ignoring the bugs"
    timestamps: {start: 1595529377000}
    __proto__: Object
evt: null
nonce: "abcdefgijkl1234567890"
__proto__: Object
```

### Non-Core Packages
```
atom-beautify 0.33.4
atom-clock 0.1.18
atom-runner 2.7.2
language-AHK 0.0.2
```
